controller:
  admin:
    username: "admin"
    password: "ReDe1313"
  
  serviceType: ClusterIP
  
  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - nodejs:latest
    - ws-cleanup:latest
    
  JCasC:
    defaultConfig: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "🚀 Jenkins para FIAP CI/CD - Bem-vindos!"
        
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "768Mi"

agent:
  enabled: true
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "768Mi"

persistence:
  enabled: false
  # No AWS Learner Lab, não temos acesso ao EBS CSI driver
  # Usar emptyDir (dados serão perdidos se o pod for deletado)
